"""empty message

Revision ID: 2cbf33e71188
Revises: 5337025e06e5
Create Date: 2020-01-22 22:34:13.781819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cbf33e71188'
down_revision = '5337025e06e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('trialused', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'trialused')
    # ### end Alembic commands ###
