"""empty message

Revision ID: 46ee623a6552
Revises: 2cbf33e71188
Create Date: 2020-01-22 22:35:07.729045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46ee623a6552'
down_revision = '2cbf33e71188'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('trialused', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'trialused')
    # ### end Alembic commands ###
