"""empty message

Revision ID: 68d7a9fe319c
Revises: 9f707d6afbff
Create Date: 2019-12-21 00:20:27.481013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68d7a9fe319c'
down_revision = '9f707d6afbff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animBuddyData', sa.Column('commenter_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'animBuddyData', 'users', ['commenter_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'animBuddyData', type_='foreignkey')
    op.drop_column('animBuddyData', 'commenter_id')
    # ### end Alembic commands ###
