"""empty message

Revision ID: b17882afa236
Revises: 3df070ddb9d7
Create Date: 2019-12-21 00:04:15.920901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b17882afa236'
down_revision = '3df070ddb9d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animBuddyData', sa.Column('posted', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('animBuddyData', 'posted')
    # ### end Alembic commands ###
